language: java

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - ./gradlew clean build

after_success:
#  - ./gradlew jacocoTestReport coveralls
#  - .buildscript/deploy_snapshot.sh
