language: java
jdk:
  - openjdk8

env:
  global:
  - secure: "KBLT1wQG6XJuSBHVByFTdLL1P5m0heSAGQD26hOb3b5tvBRn/qd1duOSI4Ub4vUXJRSDdJquRvL/zOxNQy88p8Qll5+nCJT53jJm6wM7+WNoxjRNwuEMKuI/sjHJKvLfsLZKvy9ntkFOLoLC9pah12ZO7IrepJ6+j1q9bggeKDewJiXVh/g70yoSIUjJVbMJ8rnuB8Bi1YPbBFg2K4cXSNeUZv97HkUYGPsQs8NA6B9tlMiXl8wKb4bukcXsMzAT5mYDpfkujVv7kf2XCE2OgZxIIES9Oez4QTO0WXm/OQEExl+tfLUpGO1TBXQGmsMqTSCL4trJSkyqKKyW7gQLJskCRmPLCcKkZIPn5r+wpCeNZWBJcT2T7lz6h6h28uxF39d4i4gepf5fA6LUj1+SmkX6tbIJfIw1mL392Ofa5/Gj+PleY7AIVkq5KfQiPGCZKtalebI5TNQ5mX0E4dFt+2e7yQ7PnC7jZTo+ZO+Gd0oVH2Bqm0ZGaQLL1JMD9WWOGyozAqhbIN9qFUe2PmpRc10FjEg03p37AcSqRQWnWnxoiSNUedLNFvVpn4B7cPvniGf/s5XsO6q/Qpi0mHeWtGX/UjmqF1v3ysOklW59LdbViR9QWq+Kj1T2gQ7sDZblSdxFsokEX+2IAQWjlAVb8fYgCngmnrvna2EMuMxnbno="
  - secure: "uLwtg7rD+XF1GR48mz5rtd0BpK3isRJFMPiWMbwTqHDXQE19Ma4V9y4MKcgdvULR0Gc1jdMpAlpKFBqvGTiPWrR1AKJedXWbeaOhd5no0htJD1LeLR1f9GnDrkjA2CMBRjL+ifT3wM0G9eE6hXhDr97PvwrkIWblxISq6SaKWNDxQ3sYm7YzC+pa2AVcjZEzAuz+yaehwg0ngTOxjc+P1cS/eDFN8Gq4X6JAxnDN5yQI51nCXhXuUutveAqGOn7mxt3RknvfTXtAdPDYk8TqlUh8VJyZFqwS0ZxYkVX4gI8tHHaAWwCvmRm9HaYqpbCecuS2KcWl90vkncBvii6jXIHLpRqu1Pk6HZKhWQ3867pJPOiWtzXM9v9+hKwpsZbDJvHmIzjdchp+8KTkj1tnwXq4n/icEu3NSxGm/A3DcrwYEmsOblTlAv4gGYHFn7xO6wTcU+YoaoJpzt1TUcnLqgMaEQnWy4uMXmxLd3Z+WIkT2KYeaE3kN5QnlrW3jNWncSAzwepQC1BlaWlhSZepIN4hF05bEC5X6DO0Oy+jBu3IFBIVGYyzVvmpiYgEFL+yJxgD5LQeAE+A4l/MG7Cs9dBwiZ9fnNm+FC5xnliSRfiTSZK+QqOM9HhgqxVFkrXxd9k0vU5FRyEht4Ka4iMAvxRthEA34s2xAVrY5prLm8U="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - ./gradlew clean build

before_install:
  - chmod +x .buildscript/deploy_snapshot.sh

after_success:
#  - ./gradlew jacocoTestReport coveralls
  - .buildscript/deploy_snapshot.sh
